# It contains all the configs required in the project
#yaml file r easy to readn maintain 

data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages
  model_dir: model
  init_model_file: init_model.h5
  trained_model_file: trained_model.h5

params:
  img_shape: [180,180,3] # bracket is not in square format'()' but in tuple format  '[]', if they are () format it will consider 
  #it as a string and throw error
  lr: 0.001 #Adams --> learning rate
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  validation_split: 0.2
  batch_size: 32
  seed: 42
  buffer_size: 32
  epochs: 1